set dotenv-load := true

default: (one "42")

one seed:
    OpenSCAD  \
        -o blobby_{{seed}}_prepared.stl \
        --export-format binstl \
        -D "seed={{seed}}" \
        blobby_preparation.scad